[build]
build-std = true

[target.x86_64-pc-windows-msvc]
image = "ghcr.io/cross-rs/x86_64-pc-windows-msvc-cross:local"

[target.x86_64-pc-windows-gnullvm]
image = "ghcr.io/taiki-e/rust-cross-toolchain:x86_64-pc-windows-gnullvm-dev"