// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class TrueTraceNative
    {
        const string __DllName = "version";



        [DllImport(__DllName, EntryPoint = "ComputeShader_Load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ComputeShader* ComputeShader_Load(byte* shader);

        [DllImport(__DllName, EntryPoint = "ComputeShader_Dispatch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ComputeShader_Dispatch(ComputeShader* _self, uint kernel_index, uint x, uint y, uint z);

        [DllImport(__DllName, EntryPoint = "ComputeShader_DispatchIndirect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ComputeShader_DispatchIndirect(ComputeShader* _self, uint kernel_index, void* buf, nuint buf_size);

        [DllImport(__DllName, EntryPoint = "ComputeShader_FindKernel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint ComputeShader_FindKernel(ComputeShader* _self, byte* name);

        [DllImport(__DllName, EntryPoint = "ComputeShader_SetBool", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ComputeShader_SetBool(ComputeShader* _self, byte* name, [MarshalAs(UnmanagedType.U1)] bool val);

        [DllImport(__DllName, EntryPoint = "ComputeShader_SetBuffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ComputeShader_SetBuffer(ComputeShader* _self, uint kernel_index, byte* name, void* buf, nuint buf_size);

        [DllImport(__DllName, EntryPoint = "ComputeShader_SetFloat", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ComputeShader_SetFloat(ComputeShader* _self, byte* name, float val);

        [DllImport(__DllName, EntryPoint = "ComputeShader_SetInt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ComputeShader_SetInt(ComputeShader* _self, byte* name, int val);

        [DllImport(__DllName, EntryPoint = "ComputeShader_SetMatrix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ComputeShader_SetMatrix(ComputeShader* _self, byte* name, byte* mat);

        [DllImport(__DllName, EntryPoint = "ComputeShader_SetTexture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ComputeShader_SetTexture(ComputeShader* _self, uint kernel_index, byte* name, void* tex, uint width, uint height, uint format, int dimension, uint mipCnt);

        [DllImport(__DllName, EntryPoint = "ComputeShader_SetVector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ComputeShader_SetVector(ComputeShader* _self, byte* name, byte* val);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ComputeShader
    {
    }



}
